name: Build check (Android)
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - android-port
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - android-port
    types:
      - opened
      - synchronize
      - reopened

env:
  VCPKG_ROOT: "${{github.workspace}}/dependencies/vcpkg"
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
  VCPKG_FORCE_DOWNLOADED_BINARIES: true

jobs:
  build-android:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y gettext mono-complete

      - name: Uncompile message catalogs
        run: |
          for mo_file in bin/resources/*/cemu.mo
          do
            echo $mo_file
            language_code=$(basename $(dirname $mo_file))
            po_file=src/android/app/src/main/assets/translations/$language_code/cemu.po
            mkdir -p $(dirname $po_file)
            msgunfmt $mo_file -o $po_file || echo "Failed to uncompile message catalog from $mo_file"
          done

      - name: Setup vcpkg binary cache
        uses: ./.github/actions/set-up-vcpkg-binary-cache-action
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build Cemu
        env:
          ANDROID_STORE_FILE_BASE64: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        run: |
          export JAVA_HOME=$JAVA_HOME_21_X64

          cd ./src/android

          if [[ -n "$ANDROID_STORE_FILE_BASE64" ]]; then
            base64 --decode <<< "${ANDROID_STORE_FILE_BASE64}" > store.jks
            export ANDROID_STORE_FILE=$(pwd)/store.jks
            echo "Android signing store file has been set up."
          else
            echo "No Android signing store file provided. The APK will not be signed with a release key."
          fi

          ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cemu-bin-android
          path: ./src/android/app/build/outputs/apk/*/*.apk
